// <auto-generated />
namespace WSC_E_Commerce_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intitial12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intitial12));
        
        string IMigrationMetadata.Id
        {
            get { return "201612030933506_intitial12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
